export enum Mutations {
    SET_CURRENT_TORRENT_ID = 'SET_CURRENT_TORRENT_ID',
    SET_CURRENT_TORRENT = 'SET_CURRENT_TORRENT',
    UPDATE_TORRENT_DOWNLOADING = 'UPDATE_TORRENT_DOWNLOADING',
    SET_TORRENT_DONE = 'SET_TORRENT_DONE',
    SET_TORRENT_ERROR = 'SET_TORRENT_ERROR'
}

export enum Actions {
    SET_NEW_TORRENT = 'SET_NEW_TORRENT'
}
